---
language: python
python: "2.7.13"
sudo: required

services:
  - docker
install:
  - pip install ansible==2.3.1.0
  - pip install molecule==1.25.0
  - pip install docker
script:
  - systemctl --user --global enable gpg-agent.socket
  - systemctl --user --global enable gpg-agent-ssh.socket
  - pushd tests/single-mode
  - travis_wait 30 molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
