---
language: python
python: "2.7.13"
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible python-pip python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev
install:
  - sudo pip install molecule
  - sudo pip install docker
script:
  - pushd tests/single-mode
  - travis_wait 30 sudo molecule test
  - popd
  - pushd tests/cluster-mode
  - travis_wait 30 sudo molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/