---
language: python
python: "2.7.13"
sudo: required
dist: trusty
group: deprecated-2017Q4

services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - travis_wait 30 molecule test -s single

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
