---
dist: xenial
language: python
python: "3.7"
sudo: required

services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8
script:
  - travis_wait 30 pipenv run molecule test -s single
  - travis_wait 30 pipenv run molecule test -s cluster

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
