---

- name: REDIS | Create redis group
  group:
    name: "{{ redis_group }}"
    state: present
  when: not redis_is_installed

- name: REDIS | Create redis user
  user:
    name: "{{ redis_user }}"
    group: "{{ redis_group }}"
  when: not redis_is_installed

- name: REDIS | Create log directory
  file:
    path: "{{ redis_log_path }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    state: directory
    mode: 0755
  when: not redis_is_installed and redis_confs.logfile is defined

- name: REDIS | Create log file
  file:
    path: "{{ redis_confs.logfile }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    state: touch
    mode: 0644
  when: not redis_is_installed and redis_confs.logfile is defined

- name: REDIS | Remove instance from cluster
  command: "{{ redis_conf_path }}/upgrading-helper.sh delete"
  when:
    - redis_install_new_version
    - redis_mode == 'cluster'

- name: REDIS | Stop node
  service:
    name: redis-server
    state: stopped
  when:
    - redis_install_new_version
    - redis_mode == 'cluster'

- name: REDIS | Remove existing install folder
  file:
    state: absent
    path: "{{ redis_install_path }}"
  when: not redis_is_installed or redis_install_new_version

- name: REDIS | install required libs
  apt:
    name: "{{ redis_required_libs }}"
    update_cache: yes

- name: REDIS | install cluster required libs
  apt:
    name: "{{ redis_required_libs_cluster }}"
    update_cache: yes
  when: redis_mode == 'cluster'

- name: REDIS | Download sources
  get_url:
    url: "{{ redis_source_url }}"
    dest: /tmp
    validate_certs: no
  when: not redis_is_installed or redis_install_new_version

- name: REDIS | Extract sources
  unarchive:
    copy: no
    src: /tmp/redis-{{ redis_version }}.tar.gz
    dest: /tmp
  when: not redis_is_installed or redis_install_new_version

- name: REDIS | Move sources to install path
  command: "mv /tmp/redis-{{ redis_version }}/ {{ redis_install_path }}"
  when: not redis_is_installed or redis_install_new_version

- name: REDIS | Make
  make:
    chdir: "{{ redis_install_path }}"
  when: not redis_is_installed or redis_install_new_version

- name: REDIS | Make test
  make:
    chdir: "{{ redis_install_path }}"
    target: test
  when: not redis_is_installed or redis_install_new_version

- name: REDIS | Make install
  make:
    chdir: "{{ redis_install_path }}"
    target: install
  become: yes
  when: not redis_is_installed or redis_install_new_version

- name: REDIS | install redis gem
  gem:
    name: redis
    state: present
  become: yes
  when: redis_mode == 'cluster'
