---

- name: REDIS | Check
  include: check.yml
  tags:
    - check

- name: REDIS | Install
  include: install.yml
  tags:
    - install

- name: REDIS | Configure
  include: config.yml
  tags:
    - configure

- name: REDIS | Operating System Configure
  include: os-config.yml
  tags:
    - os-configure
  when: redis_os_tuning

- name: REDIS | Service
  include: service.yml
  tags:
    - service
