---

- name: REDIS | Configuring service
  systemd:
    name: redis-server
    state: "{{ redis_service_state }}"
    enabled: "{{ redis_service_enabled }}"
    daemon_reload: yes
  when: redis_is_installed == False or redis_installed_version != redis_request_version
