---

- name: restart redis
  service:
    name: redis-server
    state: restarted

  when: redis_service_state != 'stopped'

- name: oneshot disable thp
  systemd:
    name: disable_thp
    state: restarted


