---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/.yamllint
platforms:
  - name: redis.cont
    groups:
      - redis
    image: geerlingguy/docker-debian9-ansible:latest
    privileged: True
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: single
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: False
