---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vito
    groups:
      - redis
    image: geerlingguy/docker-debian9-ansible:latest
    hostname: vito
    privileged: False
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'

  - name: sonny
    groups:
      - redis
    image: geerlingguy/docker-debian9-ansible:latest
    hostname: sonny
    privileged: False
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'

  - name: michael
    groups:
      - redis
    image: geerlingguy/docker-debian9-ansible:latest
    hostname: michael
    privileged: False
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'

lint:
  name: yamllint
  options:
    config-file: .yamllint
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    skip-tags: os-configure
scenario:
  name: cluster
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: False
