---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vito
    groups:
      - redis
    image: ${DOCKER_IMAGE_BASE:-debian:buster-slim}
    hostname: vito
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - /redis
      - /tmp
      - /run
    command: '/lib/systemd/systemd'

  - name: sonny
    groups:
      - redis
    image: ${DOCKER_IMAGE_BASE:-debian:buster-slim}
    hostname: sonny
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - /redis
      - /tmp
      - /run
    command: '/lib/systemd/systemd'

  - name: michael
    groups:
      - redis
    image: ${DOCKER_IMAGE_BASE:-debian:buster-slim}
    hostname: michael
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - /redis
      - /tmp
      - /run
    command: '/lib/systemd/systemd'

lint:
  name: yamllint
  options:
    config-file: .yamllint
provisioner:
  name: ansible
  inventory:
    group_vars:
      redis:
        redis_version: ${REDIS_VERSION:-"5.0.5"}
        redis_cluster_single: ${REDIS_CLUSTER_LEGACY:-false}
        redis_ruby_gem_version: ${REDIS_RUBY_GEM:-4.1.3}
  lint:
    name: ansible-lint
scenario:
  name: cluster
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: false
